/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#pragma once

#include "AnimationEffectTimingReadOnly.h"
#include "JSDOMWrapper.h"
#include <wtf/NeverDestroyed.h>

namespace WebCore {

class JSAnimationEffectTimingReadOnly : public JSDOMWrapper<AnimationEffectTimingReadOnly> {
public:
    using Base = JSDOMWrapper<AnimationEffectTimingReadOnly>;
    static JSAnimationEffectTimingReadOnly* create(JSC::Structure* structure, JSDOMGlobalObject* globalObject, Ref<AnimationEffectTimingReadOnly>&& impl)
    {
        JSAnimationEffectTimingReadOnly* ptr = new (NotNull, JSC::allocateCell<JSAnimationEffectTimingReadOnly>(globalObject->vm().heap)) JSAnimationEffectTimingReadOnly(structure, *globalObject, WTFMove(impl));
        ptr->finishCreation(globalObject->vm());
        return ptr;
    }

    static JSC::JSObject* createPrototype(JSC::VM&, JSDOMGlobalObject&);
    static JSC::JSObject* prototype(JSC::VM&, JSDOMGlobalObject&);
    static AnimationEffectTimingReadOnly* toWrapped(JSC::VM&, JSC::JSValue);
    static void destroy(JSC::JSCell*);

    DECLARE_INFO;

    static JSC::Structure* createStructure(JSC::VM& vm, JSC::JSGlobalObject* globalObject, JSC::JSValue prototype)
    {
        return JSC::Structure::create(vm, globalObject, prototype, JSC::TypeInfo(JSC::ObjectType, StructureFlags), info());
    }

    static JSC::JSValue getConstructor(JSC::VM&, const JSC::JSGlobalObject*);
protected:
    JSAnimationEffectTimingReadOnly(JSC::Structure*, JSDOMGlobalObject&, Ref<AnimationEffectTimingReadOnly>&&);

    void finishCreation(JSC::VM&);
};

class JSAnimationEffectTimingReadOnlyOwner : public JSC::WeakHandleOwner {
public:
    virtual bool isReachableFromOpaqueRoots(JSC::Handle<JSC::Unknown>, void* context, JSC::SlotVisitor&);
    virtual void finalize(JSC::Handle<JSC::Unknown>, void* context);
};

inline JSC::WeakHandleOwner* wrapperOwner(DOMWrapperWorld&, AnimationEffectTimingReadOnly*)
{
    static NeverDestroyed<JSAnimationEffectTimingReadOnlyOwner> owner;
    return &owner.get();
}

inline void* wrapperKey(AnimationEffectTimingReadOnly* wrappableObject)
{
    return wrappableObject;
}

JSC::JSValue toJS(JSC::ExecState*, JSDOMGlobalObject*, AnimationEffectTimingReadOnly&);
inline JSC::JSValue toJS(JSC::ExecState* state, JSDOMGlobalObject* globalObject, AnimationEffectTimingReadOnly* impl) { return impl ? toJS(state, globalObject, *impl) : JSC::jsNull(); }
JSC::JSValue toJSNewlyCreated(JSC::ExecState*, JSDOMGlobalObject*, Ref<AnimationEffectTimingReadOnly>&&);
inline JSC::JSValue toJSNewlyCreated(JSC::ExecState* state, JSDOMGlobalObject* globalObject, RefPtr<AnimationEffectTimingReadOnly>&& impl) { return impl ? toJSNewlyCreated(state, globalObject, impl.releaseNonNull()) : JSC::jsNull(); }

template<> struct JSDOMWrapperConverterTraits<AnimationEffectTimingReadOnly> {
    using WrapperClass = JSAnimationEffectTimingReadOnly;
    using ToWrappedReturnType = AnimationEffectTimingReadOnly*;
};

} // namespace WebCore
